/**
 * Autogenerated by Thrift Compiler (DNA Version, Base 0.90.0)
 *
 *  @CDN Department. ChinaNetCenter 2014
 */
package com.cnc.dna.api.openQS.StatisticsReport.v1;


import java.util.Map;
import java.util.HashMap;
import com.cnc.dna.platform.thrift.TEnum;

public enum TaskGroupType implements com.cnc.dna.platform.thrift.TEnum {
  TASK_HTTP(1),
  TASK_STREAM(2),
  TASK_MOBILE(3),
  TASK_HTTP_FULLPAGE(4);

  private final int value;

  private TaskGroupType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TaskGroupType findByValue(int value) { 
    switch (value) {
      case 1:
        return TASK_HTTP;
      case 2:
        return TASK_STREAM;
      case 3:
        return TASK_MOBILE;
      case 4:
        return TASK_HTTP_FULLPAGE;
      default:
        return null;
    }
  }
}
